
/* Create table in target */
CREATE TABLE `schedule_evergreen_campaign`(
	`schedule_evergreen_campaign_id` int(11) NOT NULL  auto_increment , 
	`account_id_fk` int(11) NOT NULL  , 
	`campaign_label` varchar(200) COLLATE latin1_swedish_ci NULL  , 
	`list_id_fk` text COLLATE latin1_swedish_ci NOT NULL  , 
	`email_campaign_id_fk` text COLLATE latin1_swedish_ci NOT NULL  , 
	`smtp_id_fk` text COLLATE latin1_swedish_ci NOT NULL  , 
	`dkim_id_fk` int(11) NULL  , 
	`total` int(11) NULL  DEFAULT '0' , 
	`sent` int(11) NOT NULL  DEFAULT '0' , 
	`last_run` timestamp NULL  , 
	`status` int(11) NOT NULL  DEFAULT '1' COMMENT '0=Inactive,1=Active,' , 
	`sender_info` int(11) NOT NULL  , 
	`sch_fromname` varchar(200) COLLATE latin1_swedish_ci NULL  , 
	`sch_fromemail` varchar(200) COLLATE latin1_swedish_ci NOT NULL  , 
	`sch_bounceemail` varchar(200) COLLATE latin1_swedish_ci NOT NULL  , 
	`sch_replyemail` varchar(200) COLLATE latin1_swedish_ci NOT NULL  , 
	`opened` int(11) NULL  DEFAULT '0' , 
	`unique_opened` int(11) NULL  DEFAULT '0' , 
	`clicked` int(11) NULL  DEFAULT '0' , 
	`unique_clicked` int(11) NULL  DEFAULT '0' , 
	`show_unsub` char(1) COLLATE latin1_swedish_ci NULL  , 
	`del_status` char(1) COLLATE latin1_swedish_ci NULL  DEFAULT '0' , 
	`mask_domain_id_fk` varchar(500) COLLATE latin1_swedish_ci NULL  , 
	`masked_domain` int(11) NULL  , 
	`adk_campaign_id_fk` varchar(500) COLLATE latin1_swedish_ci NULL  , 
	`campaign_type` char(1) COLLATE latin1_swedish_ci NULL  DEFAULT '1' , 
	`bounced` int(11) NOT NULL  DEFAULT '0' , 
	`unsubscribed` int(11) NOT NULL  DEFAULT '0' , 
	`error` varchar(300) COLLATE latin1_swedish_ci NULL  , 
	`split_campaign_id_fk` varchar(500) COLLATE latin1_swedish_ci NULL  , 
	`split_winner_campaign_id` int(11) NULL  , 
	`split_winner_campaign_time` datetime NULL  , 
	`supress_domain_count` int(11) NOT NULL  DEFAULT '0' , 
	`unsubscribed_count` int(11) NOT NULL  DEFAULT '0' , 
	`bounced_count` int(11) NOT NULL  DEFAULT '0' , 
	`suppress_email_count` int(11) NOT NULL  DEFAULT '0' , 
	`spamed_count` int(11) NOT NULL  DEFAULT '0' , 
	`thread` varchar(32) COLLATE latin1_swedish_ci NULL  , 
	`custom_options` text COLLATE latin1_swedish_ci NULL  , 
	`track_open` char(1) COLLATE latin1_swedish_ci NULL  DEFAULT '1' , 
	`track_click` char(1) COLLATE latin1_swedish_ci NULL  DEFAULT '1' , 
	`st_status` char(1) COLLATE latin1_swedish_ci NULL  DEFAULT '0' , 
	`no_of_threads` int(11) NOT NULL  DEFAULT '1' , 
	`smtp_sequence` char(1) COLLATE latin1_swedish_ci NULL  DEFAULT '1' , 
	`hourly_limit` int(11) NULL  , 
	`notification_email` varchar(300) COLLATE latin1_swedish_ci NULL  , 
	`esp_setup_id_fk` varchar(500) COLLATE latin1_swedish_ci NULL  , 
	`list_type` int(11) NULL  , 
	`segment_id_fk` text COLLATE latin1_swedish_ci NULL  , 
	`count_totals` char(1) COLLATE latin1_swedish_ci NULL  DEFAULT '0' , 
	`start_datetime` datetime NULL  , 
	`schedule_on` varchar(32) COLLATE latin1_swedish_ci NULL  COMMENT 'weekly,monthly,hours,minutes' , 
	`schedule_value` int(2) NULL  DEFAULT '0' COMMENT 'value accourding to schedule_on' , 
	`sch_time` time NOT NULL  , 
	`last_executed_at` datetime NULL  , 
	`next_execution_at` datetime NULL  , 
	PRIMARY KEY (`schedule_evergreen_campaign_id`) 
) ENGINE=InnoDB DEFAULT CHARSET='latin1';


/* Alter table in target */
ALTER TABLE `user_account` 
	ADD COLUMN `notification_emails` text  COLLATE latin1_swedish_ci NULL COMMENT 'one email perline' after `parent_account_id_fk`, 
	ADD COLUMN `notification_schedule_on` varchar(8)  COLLATE latin1_swedish_ci NULL COMMENT 'monthly,weekly' after `notification_emails`, 
	ADD COLUMN `notification_schedule_value` tinyint(4)   NULL DEFAULT '0' COMMENT 'value accourding to schedule on' after `notification_schedule_on`, 
	ADD COLUMN `notification_smtp_id_fk` tinyint(4)   NULL DEFAULT '0' after `notification_schedule_value`, 
	ADD COLUMN `notification_next_execution_at` date   NULL after `notification_smtp_id_fk`, 
	ADD COLUMN `notification_last_execution_at` datetime   NULL after `notification_next_execution_at`, COMMENT='';